version: "3.9"

services:

  database:
    image: postgres
    container_name: burger_db
    volumes:
      - psql_db:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=star-burger
    env_file:
      - ./.env_db

  frontend:
    build: frontend
    container_name: burger_parcel
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir ./bundles --public-url "./"
    volumes:
      - /home/yulia/docker/bundles:/frontend/bundles
    ports:
      - "3000:3000"

  backend:
    build: backend
    container_name: burger_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /home/yulia/docker/bundles:/backend/bundles
      - /home/yulia/docker/media:/backend/media
    environment:
      - POSTGRES_NAME=star-burger
    ports:
      - "8000:8000"
    env_file:
      - ./.env
      - ./.env_db
    depends_on:
      - database

volumes:
  psql_db:
