version: "3.9"

services:

  database:
    image: postgres
    container_name: burger_db
    volumes:
      - psql_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=star-burger
    env_file:
      - ./.env

  frontend:
    build: ../frontend
    container_name: burger_parcel
    command: ./node_modules/.bin/parcel build ./bundles-src/index.js --dist-dir ./bundles --public-url "./"
    # ports:
    #   - "3000:3000"

  backend:
    build: ../backend
    container_name: burger_django
    command: gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application
    volumes:
      - ../media:/backend/media
    environment:
      - POSTGRES_NAME=star-burger
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - database

  nginx:
    build: ./nginx
    container_name: burger_nginx
    volumes:
      - ../media:/media
      - ../static:/static
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  psql_db:
