version: "3.9"

services:

  database:
    image: postgres
    container_name: burger_db
    volumes:
      - psql_db:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=star-burger
    env_file:
      - ./.env

  frontend:
    build: ../frontend
    container_name: burger_parcel
    command: ./node_modules/.bin/parcel build ./bundles-src/index.js --dist-dir ./bundles --public-url "./"
    volumes:
      - ../bundles:/frontend/bundles
    ports:
      - "3000:3000"

  backend:
    build: ../backend
    container_name: burger_django
    command: gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application
    volumes:
      - ../bundles:/backend/bundles
      - ../media:/backend/media
    environment:
      - POSTGRES_NAME=star-burger
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - database

volumes:
  psql_db:
