version: "3.9"

services:

  database:
    image: postgres
    container_name: burger_db
    volumes:
      - psql_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=star-burger
    env_file:
      - ./.env
    networks:
      - database_network

  frontend:
    build: ../frontend
    container_name: burger_parcel
    command: ./node_modules/.bin/parcel build ./bundles-src/index.js --dist-dir ./bundles --public-url "./"

  backend:
    build: ../backend
    container_name: burger_django
    command: gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application
    volumes:
      - ../media:/backend/media
    environment:
      - POSTGRES_NAME=star-burger
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - nginx_network
      - database_network

volumes:
  psql_db:

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
